# Generated by Django 5.2.5 on 2025-09-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_item_brand_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
