# Generated by Django 5.2.5 on 2025-10-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_remove_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название гардероба')),
                ('items', models.ManyToManyField(related_name='wardrobes', to='wardrobe.item')),
            ],
            options={
                'verbose_name': 'Гардероб',
                'verbose_name_plural': 'Гардеробы',
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название образа')),
                ('items', models.ManyToManyField(related_name='outfits', to='wardrobe.item')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='wardrobe.wardrobe')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
            },
        ),
    ]
