# Generated by Django 5.2.5 on 2025-10-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_wardrobe_outfit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.RemoveField(
            model_name='wardrobe',
            name='items',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата покупки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.DeleteModel(
            name='Wardrobe',
        ),
    ]
