# Generated by Django 5.2.5 on 2025-10-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_store_remove_wardrobe_items_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Фото вещи'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wardrobe.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
