# Generated by Django 5.2.5 on 2025-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0013_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
