# Generated by Django 5.2.5 on 2025-12-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0014_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
