# Generated by Django 5.2.5 on 2025-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0015_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=3, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
