# Generated by Django 5.2.5 on 2025-12-13 05:49

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0017_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, default=pyotp.random_hex, max_length=128, null=True),
        ),
    ]
